Gy/tensor
yecol/libgrape-lite pull request #10
Opened 2020-10-16 06:31 UTC by pwrliang

Implemented TensorContext based on Apache Arrow.

2020-10-16 06:56 UTC, yecol requested changes

2020-10-16 06:56 UTC, yecol commented on examples/gnn_sampler/sampler_context.h
> +#include "examples/gnn_sampler/tensor_context.h"
move to line -31

2020-10-16 06:56 UTC, yecol commented on examples/gnn_sampler/tensor_context.h
> +#include "arrow/tensor.h"
group the headers.

2020-10-16 06:56 UTC, yecol commented on examples/gnn_sampler/sampler.h
> +        if (tensor == nullptr) {
move this `if` and the `data=ctx.data()` to line 145

2020-10-19 03:14 UTC, pwrliang commented
As we discussed before, the sampler holds nothing.

2020-10-19 03:14 UTC, closed without merging